version: 2.1
jobs:
  build:
    working_directory: /dockerapp1
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run Tests and Quality Reports
          command: |
            docker build -t test -f Dockerfile.test .

  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run:
          name: Deploy Services to linux ubuntu
          command: |
            echo "A git workflow Action will take care of this"
workflows:
  main:
    jobs:
      - build:
          context: JavaAssesmentSonarCloud
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - mai